name: DynamicConfig Auto Switch (Beijing Time - Fixed Schedule)

on:
  schedule:
    # 周五 18:00（北京时间）→ 启用活动倍率
    - cron: '0 10 * * 5'
    # 周一 00:00（北京时间）→ 恢复日常倍率
    - cron: '0 16 * * 0'
  workflow_dispatch:
    inputs:
      force_mode:
        description: '手动强制模式（normal | event），留空则自动判定'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine mode (固定时间切换)
        id: setmode
        run: |
          FORCE="${{ github.event.inputs.force_mode }}"
          if [ -n "$FORCE" ]; then
            MODE="$FORCE"
          else
            # 自动判定模式仅在触发时有效
            UTC_HOUR=$(date -u +%H)
            UTC_DOW=$(date -u +%u)
            if [ "$UTC_DOW" -eq 5 ] && [ "$UTC_HOUR" -eq 10 ]; then
              MODE="event"
            else
              MODE="normal"
            fi
          fi
          echo "mode=$MODE" >> $GITHUB_OUTPUT
          echo "当前北京时间：$(date '+%Y-%m-%d %H:%M:%S')，切换为：$MODE"

      - name: Apply DynamicConfig template
        run: |
          MODE="${{ steps.setmode.outputs.mode }}"
          if [ "$MODE" = "event" ]; then
            cp DynamicConfig_Event.ini DynamicConfig.ini
          else
            cp DynamicConfig_Normal.ini DynamicConfig.ini
          fi
          echo "已应用模板：$MODE → DynamicConfig.ini"

      - name: Commit and push if changed
        run: |
          git config user.name "AutoDynamicBot"
          git config user.email "bot@server.local"

          if ! git diff --quiet -- DynamicConfig.ini; then
            git add DynamicConfig.ini
            git commit -m "Auto switch to ${{ steps.setmode.outputs.mode }} mode @ $(date '+%Y-%m-%d %H:%M:%S') (Beijing Time)"
            git push
            echo "DynamicConfig.ini 已更新并推送。"
          else
            echo "无变化，无需提交。"
          fi
