name: DynamicConfig Auto Switch (Beijing Time)

on:
  schedule:
    - cron: '0 * * * *'   # 每小时执行一次（UTC时间）
  workflow_dispatch:
    inputs:
      force_mode:
        description: '手动强制模式（normal | event），留空则自动判定'
        required: false
        default: ''

permissions:
  contents: write

env:
  TZ: Asia/Shanghai  # 设置为北京时间

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine mode (北京时间)
        id: setmode
        run: |
          FORCE="${{ github.event.inputs.force_mode }}"
          if [ -n "$FORCE" ]; then
            MODE="$FORCE"
          else
            # 获取北京时间的小时与星期
            HOUR=$(date +'%H')
            DOW=$(date +'%u')  # 1=周一 ... 7=周日

            # 判断时间段：
            # 周五 18:00（含）至周一 00:00 为活动倍率
            if [ "$DOW" -eq 5 ] && [ "$HOUR" -ge 18 ]; then
              MODE="event"
            elif [ "$DOW" -eq 6 ] || [ "$DOW" -eq 7 ]; then
              MODE="event"
            elif [ "$DOW" -eq 1 ] && [ "$HOUR" -lt 1 ]; then
              MODE="event"
            else
              MODE="normal"
            fi
          fi

          echo "mode=$MODE" >> $GITHUB_OUTPUT
          echo "当前北京时间：$(date '+%Y-%m-%d %H:%M:%S')"
          echo "当前模式：$MODE"

      - name: Apply DynamicConfig template
        run: |
          MODE="${{ steps.setmode.outputs.mode }}"
          if [ "$MODE" = "event" ]; then
            cp DynamicConfig_Event.ini DynamicConfig.ini
          else
            cp DynamicConfig_Normal.ini DynamicConfig.ini
          fi
          echo "已应用模板：$MODE → DynamicConfig.ini"

      - name: Commit and push if changed
        run: |
          git config user.name "AutoDynamicBot"
          git config user.email "bot@server.local"

          if ! git diff --quiet -- DynamicConfig.ini; then
            git add DynamicConfig.ini
            git commit -m "Auto switch to ${{ steps.setmode.outputs.mode }} mode @ $(date '+%Y-%m-%d %H:%M:%S') (Beijing Time)"
            git push
            echo "DynamicConfig.ini 已更新并推送。"
          else
            echo "无变化，无需提交。"
          fi
